// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsmfdktjhfispzgcoces.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzbWZka3RqaGZpc3B6Z2NvY2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDQ3ODMsImV4cCI6MjA2OTQyMDc4M30.K09xVcOBQzdMYgVj-kI94lhxcAw1aS0LXV9exX4knww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});